#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline


def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")

    screen_name = sys.argv[1]
    number_of_tweets = 50

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # get user timeline
    tweets = get_user_timeline(screen_name, number_of_tweets)
    if tweets is None:
        sys.exit("Screen name doesn’t exist / Screen name’s tweets are private.")

    # analyze tweets
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0:
            print(colored("{} {}".format(score, tweet), "green"))
        elif score < 0:
            print(colored("{} {}".format(score, tweet), "red"))
        else:
            print(colored("{} {}".format(score, tweet), "yellow"))


if __name__ == "__main__":
    main()
